### ISSUE TITLE
Why Rails?

### ISSUE THREAD

**Issue by bradrobertson** [pawurb/rails-pg-extras#2]
More of a question than anything. Nothing about this gem seems to be particularly "Railsy". I'm wondering why the decision was made to couple to Rails? The only thing you need is a onnection \o a database (which you can achieve right `pg` on its own). You could still offer a railtie for those using rails and also make this usable for everyone else in the ruby world.
Any interest?

**Comment by sbellware** [comment]
I don't know if this is of interest to @pawurb, but I'm going to extract a kernel from rails-pg-extras so that the same stuff can be used with raw Ruby+PG projects (like Eventide). I've set aside some time to hack on this today. It will be built with considerations for putting a Rails wrapper around it if wanted. Obviously, I'm bogarting this thread to talk about extraneous stuff, but figured it would be relevant.

I mentioned on Twitter that rails-pg-extras is such a nice, clean project that building stuff based on it is pretty straight forward. It's super nice to drop into a new codebase and not find a mess (or, i just suck at reading other people's stuff). It's so nice to see someone take real care with their open source code that it deserves praise and recognition!

**Comment by pawurb** [comment]
Keeping a rails-specific project makes it much easier to integrate into Rails apps that are vast majority of potential use cases, like you said with AR connection ready and rake tasks with preloaded environment integration. I agree the a good way to go forward would be to extract  ruby/sql generic codes to a seperate `ruby-pg-extras` gem and make it a dependency of this one. I'll work on it in the following days.

**Comment by pawurb** [comment]
I've extracted the core logic to https://github.com/pawurb/ruby-pg-extras and included it as a dependency. I am still not sure about the API so PRs to both projects are welcome :)
